### ISSUE TITLE
Qodana code quality test and report generation in CI pipeline

### ISSUE THREAD

**Issue by anisharaz** [trypear/pear-landing-page#81]
we can add qodana to github action CI to test for code quality and generate a preety report on every pull request.
ref. https://www.jetbrains.com/qodana/

**Comment by anisharaz** [comment]
if this sounds a good idea, please assign it to me. <3 @Fryingpannn

**Comment by anisharaz** [comment]
i wrote the configs that are required for this 
## qodana.yaml
```
version: "1.0"
profile:
  name: qodana.recommended
linter: jetbrains/qodana-js:latest
exclude:
  - name: Eslint
```
## .github/workflows/CodeQualityTest.yml
```
name: Build Test
on:
  pull_request:
    types: [opened, reopened]
jobs:
  qodana_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0 # a full history is required for pull request analysis
      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
```
